### ISSUE TITLE
storageClass vs storageClassName

### ISSUE THREAD

**Issue by adlerfaulkner** [CommunitySolidServer/css-helm-chart#6]
`persistentVolumeClaim.yaml` uses `persistence.storageClassName`
https://github.com/CommunitySolidServer/css-helm-chart/blob/1c594ebd041f73411a28d9bdbab9aa5385ed7b17/community-solid-server/templates/persistentVolumeClaim.yaml#L9

But `values.yaml` and the `README.md` use `persistence.storageClass`
https://github.com/CommunitySolidServer/css-helm-chart/blob/1c594ebd041f73411a28d9bdbab9aa5385ed7b17/community-solid-server/values.yaml#L77
https://github.com/CommunitySolidServer/css-helm-chart/blob/1c594ebd041f73411a28d9bdbab9aa5385ed7b17/community-solid-server/README.md?plain=1#L76

Am I not seeing some transformation or is it true that those don't line up?

**Comment by MisterTimn** [comment]
Correct, I was using a separate values file for testing which had storageClassName also, hence why this went undetected.
Will change asap!

**Comment by MisterTimn** [comment]
Fixed in ced3408b0346bd8241cc83ae939191c69f5024c8
